steps:
  - id: 'branch name'
    name:  'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo"*************"
        echo "$BRANCH_NAME"
        echo "************"

  - id: 'tf init'
    name: 'hashicrop/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
       terraform inti

  - id: 'tf plan'
    name: 'hashicrop/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
       terraform plan

  - id: 'tf apply'
    name: 'hashicrop/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
        if [["$BRANCH_NAME"=="main"]];then
           echo "Branch is 'main',proceeding with terraform apply."
           terraform apply --auto-approve
           exit 0
        else
           echo "Branch is not 'main', skipping terraform apply."
           exit 0
        fi    




