steps:
  - id: 'branch name'
    name:'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo"*************"
        echo "$BRANCH_NAME"
        echo "************"

  -id: 'tf init'
    name: 'hashicrop/terraform:5.10.0'
    entrypoint:'sh'
    args:
    - '-c'
    - | 
       terraform inti

  -id: 'tf plan'
    name: 'hashicrop/terraform:5.10.0'
    entrypoint:'sh'
    args:
    - '-c'
    - | 
       terraform plan

  -id: 'tf apply'
    name: 'hashicrop/terraform:5.10.0'
    entrypoint:'sh'
    args:
    - '-c'
    - | 
       if [["$BRANCH_NAME"=="prod"]];then
        echo "Branch is 'prod',proceeding with terraform apply."
        terraform plan
        exit 0
      else
        echo "Branch is not 'prod', skipping terraform apply."
        exit 0
      fi    




